DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
	id INTEGER PRIMARY KEY ASC,
	title text,
	story text,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TRIGGER posts BEFORE UPDATE ON posts BEGIN 
UPDATE posts SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;

DROP TABLE IF EXISTS pics;
CREATE TABLE pics (
	id INTEGER PRIMARY KEY ASC,
	url text,
	carousel integer,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TRIGGER pics BEFORE UPDATE ON pics BEGIN
UPDATE pics SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY ASC,
	pass text
);
